# Generated by Django 2.1.5 on 2021-09-11 23:56

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('blogging', '0002_categoey'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categoey',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
